### ISSUE TITLE
VMB2BLE status seems to reset to 'open' and VMB2BLE does not respond to stop cover command

### ISSUE THREAD

**Issue by gitd8400** [thomasdelaet/python-velbus#27]
VMB2BLE does not respond to stop cover command.

Also, VMB2BLE seems to reset to open after a short delay even when the actual cover is closed. Looks like status of the module is not correctly detected.

The cover down command can be issued in the interface of HA. When given a down command the status temporarily changes to closed and the interface shows a clickable cover up. It is then possible to give a cover up command and this works (but stop cover is also not possible).

**Comment by Cereal2nd** [comment]
what version os home-assistant is this?

**Comment by gitd8400** [comment]
0.96.5

**Comment by Cereal2nd** [comment]
this is solved in python-velbus
in one of the following versions of hass this will be released
