### ISSUE TITLE
Requirement is pinned for python-velbus 2.0.43: pyserial==3.3

### ISSUE THREAD

**Issue by MartinHjelmare** [thomasdelaet/python-velbus#61]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by thomasdelaet** [comment]
Thanks @MartinHjelmare  for the tip! I'll get this fixed

**Comment by Cereal2nd** [comment]
we still need to draft a new release and then update the homeAssistant manifest.yaml

**Comment by thomasdelaet** [comment]
this is already done
